"""
Find the most massive halo at z=0 in SAGE output and report its properties
and satellite population.

Also supports generating an animated GIF of the top-N cluster grid evolving
through time (same clusters tracked by GalaxyIndex).
"""

import argparse
import io
import h5py
import glob
import os
import sys
from PIL import Image

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Circle

DEFAULT_HUBBLE_H = 0.73
DEFAULT_BOX_SIZE = 62.5  # Mpc/h


def _list_model_files(output_dir: str) -> list[str]:
    files = sorted(glob.glob(os.path.join(output_dir, "model_*.hdf5")))
    if not files:
        sys.exit(f"No model_*.hdf5 files found in {output_dir}")
    return files


def load_snapshot(snap_num: int, output_dir: str = "output/millennium", fields: list[str] | None = None):
    """Load galaxies for a given snapshot (Snap_<snap_num>) across all output files.

    Parameters
    ----------
    snap_num
        Snapshot number (e.g. 63 for z=0 in Millennium).
    output_dir
        Directory containing model_*.hdf5.
    fields
        If provided, only load these datasets (faster + lower memory).
    """

    files = _list_model_files(output_dir)
    group_name = f"Snap_{snap_num}"

    chunks: dict[str, list[np.ndarray]] = {}
    loaded_any = False
    for fpath in files:
        with h5py.File(fpath, "r") as f:
            if group_name not in f:
                continue
            snap = f[group_name]
            loaded_any = True
            keys = fields if fields is not None else list(snap.keys())
            for key in keys:
                if key not in snap:
                    raise KeyError(f"Dataset {key!r} not found in {group_name} of {fpath}")
                chunks.setdefault(key, []).append(snap[key][:])

    if not loaded_any:
        sys.exit(f"No {group_name} found in any model_*.hdf5 under {output_dir}")

    return {k: np.concatenate(v, axis=0) for k, v in chunks.items()}


def _top_central_galaxy_ids_by_mvir(data, n_clusters: int) -> np.ndarray:
    centrals = data["Type"] == 0
    central_idx = np.where(centrals)[0]
    order = np.argsort(data["Mvir"][central_idx])[::-1]
    top_idx = central_idx[order[:n_clusters]]
    return data["GalaxyIndex"][top_idx]


def _ensure_plots_dir(output_dir: str) -> str:
    plots_dir = os.path.join(output_dir, "plots")
    os.makedirs(plots_dir, exist_ok=True)
    return plots_dir


def main(argv: list[str] | None = None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", default="output/millennium", help="Directory containing model_*.hdf5")
    parser.add_argument("--z0-snap", type=int, default=49, help="Snapshot to treat as z=0 (default: 63)")
    parser.add_argument("--min-len", type=int, default=20, help="Minimum Len for satellites to be considered")
    parser.add_argument("--n-clusters", type=int, default=8, help="Number of clusters in the 2x4 grid")
    parser.add_argument(
        "--make-gif",
        action="store_true",
        help="(Deprecated) Kept for compatibility; GIFs are generated by default.",
    )
    parser.add_argument("--no-gif", action="store_true", help="Skip writing the animated GIF")
    parser.add_argument("--gif-start-snap", type=int, default=0, help="First snapshot in the GIF")
    parser.add_argument(
        "--gif-end-snap",
        type=int,
        default=None,
        help="Last snapshot in the GIF (default: --z0-snap)",
    )
    parser.add_argument(
        "--gif-fps",
        type=float,
        default=None,
        help="Frames per second for the GIF (if omitted, uses make_cluster_grid_gif default)",
    )
    args = parser.parse_args(argv)

    gif_end = args.z0_snap if args.gif_end_snap is None else args.gif_end_snap
    make_gif = (not args.no_gif) or args.make_gif

    data = load_snapshot(args.z0_snap, output_dir=args.output_dir)
    ngal = len(data['Type'])
    print(f"Total galaxies at z=0: {ngal}")
    print(f"  Type 0 (centrals):    {(data['Type'] == 0).sum()}")
    print(f"  Type 1 (satellites):  {(data['Type'] == 1).sum()}")
    print(f"  Type 2 (orphans):     {(data['Type'] == 2).sum()}")
    print()

    # Find the most massive central (Type 0) by Mvir
    centrals = data['Type'] == 0
    central_idx = np.where(centrals)[0]
    most_massive = central_idx[np.argmax(data['Mvir'][central_idx])]

    central_gal_index = data['GalaxyIndex'][most_massive]

    # Find all satellites belonging to this central
    min_len = args.min_len  # minimum particle count for resolved subhaloes
    satellites = data['CentralGalaxyIndex'] == central_gal_index
    sat_mask = satellites & (data['Type'] != 0) & (data['Len'] >= min_len)

    # Unit conversions (SAGE internal units: 1e10 Msun/h)
    hubble_h = DEFAULT_HUBBLE_H
    mass_factor = 1e10 / hubble_h  # to Msun

    print("=" * 60)
    print("MOST MASSIVE HALO AT z=0")
    print("=" * 60)
    print(f"  Mvir:           {data['Mvir'][most_massive] * mass_factor:.3e} Msun")
    print(f"  Rvir:           {data['Rvir'][most_massive] / hubble_h * 1e3:.1f} kpc")
    print(f"  Vvir:           {data['Vvir'][most_massive]:.1f} km/s")
    print(f"  Vmax:           {data['Vmax'][most_massive]:.1f} km/s")
    print(f"  N_particles:    {data['Len'][most_massive]}")
    print(f"  Position:       ({data['Posx'][most_massive]:.2f}, {data['Posy'][most_massive]:.2f}, {data['Posz'][most_massive]:.2f}) Mpc/h")
    print()

    print("BCG PROPERTIES:")
    bcg_stellar = data['StellarMass'][most_massive] * mass_factor
    bcg_merger_bulge = data['MergerBulgeMass'][most_massive] * mass_factor
    merger_frac = bcg_merger_bulge / bcg_stellar if bcg_stellar > 0 else 0.0
    print(f"  Stellar mass:   {bcg_stellar:.3e} Msun")
    print(f"  Bulge mass:     {data['BulgeMass'][most_massive] * mass_factor:.3e} Msun")
    print(f"  Merger bulge:   {bcg_merger_bulge:.3e} Msun  ({merger_frac:.1%} of stellar)")
    print(f"  Cold gas:       {data['ColdGas'][most_massive] * mass_factor:.3e} Msun")
    print(f"  Hot gas:        {data['HotGas'][most_massive] * mass_factor:.3e} Msun")
    print(f"  CGM gas:        {data['CGMgas'][most_massive] * mass_factor:.3e} Msun")
    print(f"  ICS:            {data['IntraClusterStars'][most_massive] * mass_factor:.3e} Msun")
    print(f"  Black hole:     {data['BlackHoleMass'][most_massive] * mass_factor:.3e} Msun")
    print(f"  Ejected mass:   {data['EjectedMass'][most_massive] * mass_factor:.3e} Msun")
    print()

    n_sat = sat_mask.sum()
    print("=" * 60)
    print(f"SATELLITE POPULATION: {n_sat} galaxies")
    print("=" * 60)

    if n_sat > 0:
        sat_indices = np.where(sat_mask)[0]
        sat_stellar = data['StellarMass'][sat_indices] * mass_factor
        sat_mvir = data['Mvir'][sat_indices] * mass_factor

        print(f"  Total satellite stellar mass:  {sat_stellar.sum():.3e} Msun")
        print(f"  Satellite stellar mass range:  {sat_stellar.min():.3e} - {sat_stellar.max():.3e} Msun")
        print(f"  Median satellite stellar mass: {np.median(sat_stellar):.3e} Msun")
        print()

        # Compute 3D distances from central (with periodic box wrapping)
        box_size = DEFAULT_BOX_SIZE
        cx, cy, cz = data['Posx'][most_massive], data['Posy'][most_massive], data['Posz'][most_massive]
        dx = data['Posx'][sat_indices] - cx
        dy = data['Posy'][sat_indices] - cy
        dz = data['Posz'][sat_indices] - cz
        # Periodic wrapping
        dx = np.where(np.abs(dx) > box_size/2, dx - np.sign(dx)*box_size, dx)
        dy = np.where(np.abs(dy) > box_size/2, dy - np.sign(dy)*box_size, dy)
        dz = np.where(np.abs(dz) > box_size/2, dz - np.sign(dz)*box_size, dz)
        dist_3d = np.sqrt(dx**2 + dy**2 + dz**2) / hubble_h * 1e3  # kpc

        rvir_kpc = data['Rvir'][most_massive] / hubble_h * 1e3
        print(f"  Distance range from BCG:       {dist_3d.min():.1f} - {dist_3d.max():.1f} kpc")
        print(f"  Median distance from BCG:      {np.median(dist_3d):.1f} kpc")
        print(f"  Satellites within Rvir ({rvir_kpc:.0f} kpc): {(dist_3d <= rvir_kpc).sum()}")
        print()

        # Sort by stellar mass, show top 10
        order = np.argsort(sat_stellar)[::-1]
        n_show = min(10, len(order))
        print(f"  Top {n_show} satellites by stellar mass:")
        print(f"  {'#':>3}  {'M_star (Msun)':>14}  {'Mvir (Msun)':>14}  {'Type':>4}  {'Len':>6}  {'Dist (kpc)':>10}")
        print(f"  {'---':>3}  {'-'*14:>14}  {'-'*14:>14}  {'----':>4}  {'------':>6}  {'-'*10:>10}")
        for i in range(n_show):
            idx = sat_indices[order[i]]
            print(f"  {i+1:3d}  {sat_stellar[order[i]]:14.3e}  {sat_mvir[order[i]]:14.3e}  {data['Type'][idx]:4d}  {data['Len'][idx]:6d}  {dist_3d[order[i]]:10.1f}")

    # Summary of total baryonic budget
    print()
    print("=" * 60)
    print("FOF GROUP BARYONIC BUDGET")
    print("=" * 60)
    all_in_fof = satellites | (np.arange(ngal) == most_massive)
    fof_indices = np.where(all_in_fof)[0]

    total_stellar = data['StellarMass'][fof_indices].sum() * mass_factor
    total_cold = data['ColdGas'][fof_indices].sum() * mass_factor
    total_hot = data['HotGas'][fof_indices].sum() * mass_factor
    total_cgm = data['CGMgas'][fof_indices].sum() * mass_factor
    total_ics = data['IntraClusterStars'][fof_indices].sum() * mass_factor
    total_ejected = data['EjectedMass'][fof_indices].sum() * mass_factor
    total_bh = data['BlackHoleMass'][fof_indices].sum() * mass_factor

    print(f"  Stellar (all galaxies): {total_stellar:.3e} Msun")
    print(f"  Cold gas:               {total_cold:.3e} Msun")
    print(f"  Hot gas:                {total_hot:.3e} Msun")
    print(f"  CGM gas:                {total_cgm:.3e} Msun")
    print(f"  ICS:                    {total_ics:.3e} Msun")
    print(f"  Ejected mass:           {total_ejected:.3e} Msun")
    print(f"  Black holes:            {total_bh:.3e} Msun")
    total_baryons = total_stellar + total_cold + total_hot + total_cgm + total_ics + total_ejected + total_bh
    print(f"  ----------------------------------------")
    print(f"  Total baryons:          {total_baryons:.3e} Msun")
    halo_mvir = data['Mvir'][most_massive] * mass_factor
    print(f"  Baryon fraction:        {total_baryons / halo_mvir:.4f}  (cosmic = 0.17)")

    # Plot spatial map of the cluster
    plot_cluster(data, most_massive, sat_mask, hubble_h, mass_factor, output_dir=args.output_dir)

    # Plot grid of top 8 most massive clusters
    plot_cluster_grid(data, hubble_h, mass_factor, min_len=min_len, n_clusters=args.n_clusters, output_dir=args.output_dir)

    if make_gif:
        gif_kwargs = dict(
            output_dir=args.output_dir,
            n_clusters=args.n_clusters,
            min_len=min_len,
            snap_start=args.gif_start_snap,
            snap_end=gif_end,
        )
        if args.gif_fps is not None:
            gif_kwargs["fps"] = args.gif_fps
        make_cluster_grid_gif(**gif_kwargs)


def _get_satellite_offsets(data, central_idx, sat_indices, hubble_h, box_size=62.5):
    """Compute periodic-wrapped x/y offsets (Mpc) of satellites from a central."""
    cx, cy, cz = data['Posx'][central_idx], data['Posy'][central_idx], data['Posz'][central_idx]
    dx = data['Posx'][sat_indices] - cx
    dy = data['Posy'][sat_indices] - cy
    dz = data['Posz'][sat_indices] - cz
    for d in [dx, dy, dz]:
        d[np.abs(d) > box_size/2] -= np.sign(d[np.abs(d) > box_size/2]) * box_size
    return dx / hubble_h, dy / hubble_h


def _plot_cluster_panel(ax, data, central_idx, sat_indices, hubble_h, mass_factor,
                        box_size=62.5, show_colorbar=True, title_fontsize=12, fixed_lim=None):
    """Plot a single cluster panel on the given axes."""
    if central_idx is None:
        ax.text(0.5, 0.5, "missing", transform=ax.transAxes, ha="center", va="center")
        if fixed_lim is not None:
            ax.set_xlim(-fixed_lim, fixed_lim)
            ax.set_ylim(-fixed_lim, fixed_lim)
        ax.set_aspect('equal')
        ax.set_xticks([])
        ax.set_yticks([])
        return None

    dx_mpc, dy_mpc = _get_satellite_offsets(data, central_idx, sat_indices, hubble_h, box_size)
    sat_stellar = data['StellarMass'][sat_indices] * mass_factor
    rvir_mpc = data['Rvir'][central_idx] / hubble_h

    # Rvir circle
    ax.add_patch(Circle((0, 0), rvir_mpc, fill=False, linestyle='--', color='grey', linewidth=1.5))

    # FOF extent circle
    if len(sat_indices) > 0:
        fof_extent = np.max(np.sqrt(dx_mpc**2 + dy_mpc**2))
        ax.add_patch(Circle((0, 0), fof_extent, fill=False, linestyle=':', color='steelblue', linewidth=1.5))

    # Satellites (exclude zero-mass)
    has_stars = sat_stellar > 0
    sc = None
    if has_stars.any():
        log_mstar = np.log10(sat_stellar[has_stars])
        sizes = 10 + 90 * (log_mstar - log_mstar.min()) / max(log_mstar.max() - log_mstar.min(), 0.1)
        sc = ax.scatter(dx_mpc[has_stars], dy_mpc[has_stars], s=sizes, c=log_mstar, cmap='plasma',
                        edgecolors='k', linewidths=0.5, zorder=3)
        if show_colorbar:
            cbar = plt.colorbar(sc, ax=ax, shrink=0.8, pad=0.02)
            cbar.set_label(r'log$_{10}$($M_{\star,\mathrm{sat}}$ / M$_\odot$)', fontsize=10)

    # BCG
    bcg_stellar = data['StellarMass'][central_idx] * mass_factor
    bcg_merger_bulge = data['MergerBulgeMass'][central_idx] * mass_factor
    merger_frac = bcg_merger_bulge / bcg_stellar if bcg_stellar > 0 else 0.0
    bcg_size = 300 + 700 * merger_frac
    ax.scatter(0, 0, s=bcg_size, c='dodgerblue', marker='*', edgecolors='k', linewidths=0.8, zorder=5)

    # Title
    mvir = data['Mvir'][central_idx] * mass_factor
    ics_mass = data['IntraClusterStars'][central_idx] * mass_factor
    ax.set_title(f'$M_{{vir}}$ = {mvir:.2e} M$_\\odot$\n'
                 f'{len(sat_indices)} sats, ICS = {ics_mass:.2e} M$_\\odot$',
                 fontsize=title_fontsize)

    # Formatting
    if fixed_lim is not None:
        lim = fixed_lim
    else:
        if len(sat_indices) > 0:
            lim = max(rvir_mpc * 1.5, np.max(np.sqrt(dx_mpc**2 + dy_mpc**2)) * 1.15)
        else:
            lim = rvir_mpc * 1.5
    ax.set_xlim(-lim, lim)
    ax.set_ylim(-lim, lim)
    ax.set_aspect('equal')
    ax.axhline(0, color='grey', alpha=0.2, linewidth=0.5)
    ax.axvline(0, color='grey', alpha=0.2, linewidth=0.5)

    return sc


def plot_cluster(data, most_massive, sat_mask, hubble_h, mass_factor, output_dir="output/millennium"):
    """2D projected view of the most massive cluster."""
    sat_indices = np.where(sat_mask)[0]

    fig, ax = plt.subplots(figsize=(8, 8))
    sc = _plot_cluster_panel(ax, data, most_massive, sat_indices, hubble_h, mass_factor)
    ax.set_xlabel('$\\Delta x$ (Mpc)', fontsize=12)
    ax.set_ylabel('$\\Delta y$ (Mpc)', fontsize=12)

    plt.tight_layout()
    plots_dir = _ensure_plots_dir(output_dir)
    outpath = os.path.join(plots_dir, 'cluster_map.pdf')
    plt.savefig(outpath, dpi=150)
    print(f"\nPlot saved to {outpath}")
    plt.close()


def plot_cluster_grid(data, hubble_h, mass_factor, min_len=100, n_clusters=8, output_dir="output/millennium"):
    """2x4 grid of the top N most massive clusters."""
    centrals = data['Type'] == 0
    central_idx = np.where(centrals)[0]
    # Sort centrals by Mvir descending, take top n_clusters
    order = np.argsort(data['Mvir'][central_idx])[::-1]
    top_centrals = central_idx[order[:n_clusters]]

    fig, axes = plt.subplots(2, 4, figsize=(20, 10))

    for i, (ax, ci) in enumerate(zip(axes.flat, top_centrals)):
        gal_idx = data['GalaxyIndex'][ci]
        sat_mask = (data['CentralGalaxyIndex'] == gal_idx) & (data['Type'] != 0) & (data['Len'] >= min_len)
        sat_indices = np.where(sat_mask)[0]

        _plot_cluster_panel(ax, data, ci, sat_indices, hubble_h, mass_factor, show_colorbar=False,
                            title_fontsize=10)

        if i >= 4:
            ax.set_xlabel('$\\Delta x$ (Mpc)', fontsize=10)
        if i % 4 == 0:
            ax.set_ylabel('$\\Delta y$ (Mpc)', fontsize=10)

    fig.suptitle(f'Top {n_clusters} most massive clusters at z=0', fontsize=14, y=1.01)
    plt.tight_layout()
    plots_dir = _ensure_plots_dir(output_dir)
    outpath = os.path.join(plots_dir, 'cluster_grid.pdf')
    plt.savefig(outpath, dpi=150, bbox_inches='tight')
    print(f"Grid plot saved to {outpath}")
    plt.close()


def make_cluster_grid_gif(
    output_dir: str = "output/millennium",
    n_clusters: int = 8,
    min_len: int = 50,
    snap_start: int = 0,
    snap_end: int = 63,
    fps: float = 2.0,
    dpi: int = 120,
):
    """Write an animated GIF of the top-N z=0 clusters evolving across snapshots."""

    if snap_end < snap_start:
        raise ValueError("snap_end must be >= snap_start")

    hubble_h = DEFAULT_HUBBLE_H
    mass_factor = 1e10 / hubble_h
    box_size = DEFAULT_BOX_SIZE

    fields = [
        "Type",
        "GalaxyIndex",
        "CentralGalaxyIndex",
        "Len",
        "StellarMass",
        "MergerBulgeMass",
        "Mvir",
        "Rvir",
        "IntraClusterStars",
        "Posx",
        "Posy",
        "Posz",
    ]

    # Choose the cluster set from the final snapshot so the same objects appear in every frame.
    z0_data = load_snapshot(snap_end, output_dir=output_dir, fields=fields)
    central_ids = _top_central_galaxy_ids_by_mvir(z0_data, n_clusters=n_clusters)

    # Fix axis limits per panel based on the z=0 extent (reduces frame-to-frame jitter).
    fixed_lims = []
    for gid in central_ids:
        matches = np.where(z0_data["GalaxyIndex"] == gid)[0]
        if len(matches) == 0:
            fixed_lims.append(None)
            continue
        ci = int(matches[0])
        sat_mask = (
            (z0_data["CentralGalaxyIndex"] == gid)
            & (z0_data["Type"] != 0)
            & (z0_data["Len"] >= min_len)
        )
        sat_indices = np.where(sat_mask)[0]
        rvir_mpc = z0_data["Rvir"][ci] / hubble_h
        if len(sat_indices) > 0:
            dx_mpc, dy_mpc = _get_satellite_offsets(z0_data, ci, sat_indices, hubble_h, box_size=box_size)
            lim = max(rvir_mpc * 1.5, np.max(np.sqrt(dx_mpc**2 + dy_mpc**2)) * 1.15)
        else:
            lim = rvir_mpc * 1.5
        fixed_lims.append(float(lim))

    frames: list[Image.Image] = []
    for snap in range(snap_start, snap_end + 1):
        data = load_snapshot(snap, output_dir=output_dir, fields=fields)

        fig, axes = plt.subplots(2, 4, figsize=(20, 10))
        for i, (ax, gid) in enumerate(zip(axes.flat, central_ids)):
            matches = np.where(data["GalaxyIndex"] == gid)[0]
            ci = int(matches[0]) if len(matches) > 0 else None
            if ci is None:
                _plot_cluster_panel(
                    ax,
                    data,
                    None,
                    np.array([], dtype=int),
                    hubble_h,
                    mass_factor,
                    box_size=box_size,
                    show_colorbar=False,
                    title_fontsize=10,
                    fixed_lim=fixed_lims[i],
                )
            else:
                sat_mask = (
                    (data["CentralGalaxyIndex"] == gid)
                    & (data["Type"] != 0)
                    & (data["Len"] >= min_len)
                )
                sat_indices = np.where(sat_mask)[0]
                _plot_cluster_panel(
                    ax,
                    data,
                    ci,
                    sat_indices,
                    hubble_h,
                    mass_factor,
                    box_size=box_size,
                    show_colorbar=False,
                    title_fontsize=10,
                    fixed_lim=fixed_lims[i],
                )

            if i >= 4:
                ax.set_xlabel('$\\Delta x$ (Mpc)', fontsize=10)
            if i % 4 == 0:
                ax.set_ylabel('$\\Delta y$ (Mpc)', fontsize=10)

        fig.suptitle(f"Top {n_clusters} z=0 clusters: evolution (Snap_{snap})", fontsize=14, y=1.01)
        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png", dpi=dpi, bbox_inches="tight")
        plt.close(fig)
        buf.seek(0)
        img = Image.open(buf).convert("RGBA").copy()
        buf.close()
        frames.append(img)

    if not frames:
        raise RuntimeError("No frames generated")

    plots_dir = _ensure_plots_dir(output_dir)
    outpath = os.path.join(plots_dir, "cluster_grid_evolution.gif")
    duration_ms = int(round(1000.0 / max(fps, 0.1)))
    frames[0].save(outpath, save_all=True, append_images=frames[1:], duration=duration_ms, loop=0)
    print(f"GIF saved to {outpath}")


if __name__ == "__main__":
    main()
