import numpy as np
from colossus.cosmology import cosmology
from colossus.halo import concentration

# 1. Set the cosmology
# Define a custom cosmology dictionary using the Millennium Simulation parameters 
# as a baseline so you can easily tweak them later.
custom_params = {
    'flat': True,
    'H0': 73.0,
    'Om0': 0.25,
    'Ob0': 0.045,
    'sigma8': 0.90,
    'ns': 1.0,
    'relspecies': False # The Millennium simulation ignored relativistic species
}
cosmo = cosmology.setCosmology('custom_millennium', **custom_params)

# 2. Define the grid boundaries
log_masses = np.round(np.arange(6.0, 16.1, 0.2), 2) 
redshifts = np.round(np.arange(0.0, 18.1, 0.5), 2)  

def generate_both_tables():
    # Pre-compute the values so we only run Colossus once
    table_vals = []
    for lm in log_masses:
        M = 10**lm
        row_vals = []
        for z_val in redshifts:
            try:
                # Calculate Ishiyama+21 concentration
                c = concentration.concentration(M, '200c', z_val, model='ishiyama21')
                row_vals.append(f"{c:.3f}")
            except Exception:
                # Fallback for unphysical regimes
                row_vals.append("-1.000") 
        table_vals.append(row_vals)

    mass_str = ", ".join([f"{m:.1f}" for m in log_masses])
    z_str = ", ".join([f"{z_val:.1f}" for z_val in redshifts])

    # ==========================================
    # OUTPUT C++ FORMAT
    # ==========================================
    print("================ C++ FORMAT ================\n")
    print(f"// Ishiyama+21 concentration-mass lookup table (mdef=200c, halo_sample=all, c_type=fit)")
    print(f"// Generated by Colossus with {cosmo.name} cosmology")
    print(f"// Rows: log10(Mvir / [Msun/h]), Columns: redshift\n")
    
    print(f"#define CM_TABLE_N_MASS {len(log_masses)}")
    print(f"#define CM_TABLE_N_Z {len(redshifts)}")
    print(f"const double cm_table_logmass[CM_TABLE_N_MASS] = {{{mass_str}}};")
    print(f"const double cm_table_z[CM_TABLE_N_Z] = {{{z_str}}};")
    print("const double cm_table[CM_TABLE_N_MASS][CM_TABLE_N_Z] = {")
    for i, row in enumerate(table_vals):
        row_str = ", ".join(row)
        comma = "," if i < len(table_vals) - 1 else ""
        print(f"    {{{row_str}}}{comma}")
    print("};\n")

    # ==========================================
    # OUTPUT PYTHON FORMAT
    # ==========================================
    # print("================ PYTHON FORMAT ================\n")
    # print("# Full Ishiyama+21 lookup table (all redshifts) for threshold computation")
    # print(f"# Generated by Colossus with {cosmo.name} cosmology")
    # print(f"_CM_LOGMASS = np.array([{mass_str}])")
    # print(f"_CM_Z = np.array([{z_str}])")
    # print("_CM_TABLE = np.array([")
    # for i, row in enumerate(table_vals):
    #     row_str = ", ".join(row)
    #     comma = "," if i < len(table_vals) - 1 else ""
    #     print(f"    [{row_str}]{comma}")
    # print("])\n")

if __name__ == "__main__":
    generate_both_tables()